services:
  app1:
    build: .
    environment:
      DATABASE_NAME: hackathon_db
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  app2:
    build: .
    environment:
      DATABASE_NAME: hackathon_db
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
      REDIS_HOST: redis
      REDIS_PORT: 6379
    depends_on:
      db:
        condition: service_healthy
      redis:
        condition: service_started
    restart: always

  nginx:
    image: nginx:alpine
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app1
      - app2
    restart: always

  redis:
    image: redis:7-alpine
    restart: always

  seeder:
    build: .
    environment:
      DATABASE_NAME: hackathon_db
      DATABASE_HOST: db
      DATABASE_PORT: 5432
      DATABASE_USER: postgres
      DATABASE_PASSWORD: postgres
    depends_on:
      db:
        condition: service_healthy
    command: sh -c "sleep 15 && uv run python seed.py --fresh"
    restart: "no"

  db:
    image: postgres:15
    environment:
      POSTGRES_DB: hackathon_db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
    volumes:
      - pgdata:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres"]
      interval: 5s
      timeout: 5s
      retries: 5

volumes:
  pgdata:
